
package schema

import (
	"github.com/jinzhu/gorm"
)

func Migrate(db *gorm.DB) error {
	db.AutoMigrate(&AmazonCognitoSync{})
	db.AutoMigrate(&AWSCodeDeploy{})
	db.AutoMigrate(&AWSDeviceFarm{})
	db.AutoMigrate(&AmazonVPC{})
	db.AutoMigrate(&AWSSupportBusiness{})
	db.AutoMigrate(&AmazonKinesisFirehose{})
	db.AutoMigrate(&AWSIoT{})
	db.AutoMigrate(&Awswaf{})
	db.AutoMigrate(&AmazonAthena{})
	db.AutoMigrate(&AWSSupportEnterprise{})
	db.AutoMigrate(&ElasticMapReduce{})
	db.AutoMigrate(&AWSCloudTrail{})
	db.AutoMigrate(&AWSStorageGateway{})
	db.AutoMigrate(&AmazonEC2{})
	db.AutoMigrate(&AWSServiceCatalog{})
	db.AutoMigrate(&AWSDeveloperSupport{})
	db.AutoMigrate(&AmazonLex{})
	db.AutoMigrate(&AmazonECR{})
	db.AutoMigrate(&AWSLambda{})
	db.AutoMigrate(&AmazonWAM{})
	db.AutoMigrate(&AmazonStates{})
	db.AutoMigrate(&AmazonChime{})
	db.AutoMigrate(&AWSQueueService{})
	db.AutoMigrate(&AmazonS3{})
	db.AutoMigrate(&AWSConfig{})
	db.AutoMigrate(&AlexaTopSites{})
	db.AutoMigrate(&AmazonGameLift{})
	db.AutoMigrate(&AmazonCloudWatch{})
	db.AutoMigrate(&AWSCodePipeline{})
	db.AutoMigrate(&AmazonWorkDocs{})
	db.AutoMigrate(&AmazonML{})
	db.AutoMigrate(&AmazonRedshift{})
	db.AutoMigrate(&AWSBudgets{})
	db.AutoMigrate(&AmazonRoute53{})
	db.AutoMigrate(&AmazonWorkSpaces{})
	db.AutoMigrate(&AmazonKinesis{})
	db.AutoMigrate(&Datapipeline{})
	db.AutoMigrate(&AmazonES{})
	db.AutoMigrate(&AmazonInspector{})
	db.AutoMigrate(&AmazonApiGateway{})
	db.AutoMigrate(&AmazonKinesisAnalytics{})
	db.AutoMigrate(&AmazonSNS{})
	db.AutoMigrate(&Awskms{})
	db.AutoMigrate(&Mobileanalytics{})
	db.AutoMigrate(&IngestionService{})
	db.AutoMigrate(&AmazonCloudFront{})
	db.AutoMigrate(&AmazonSWF{})
	db.AutoMigrate(&AmazonGlacier{})
	db.AutoMigrate(&AWSDirectoryService{})
	db.AutoMigrate(&AmazonCloudSearch{})
	db.AutoMigrate(&AmazonElastiCache{})
	db.AutoMigrate(&AmazonDynamoDB{})
	db.AutoMigrate(&AmazonPolly{})
	db.AutoMigrate(&AmazonSimpleDB{})
	db.AutoMigrate(&AWSDatabaseMigrationSvc{})
	db.AutoMigrate(&AmazonEFS{})
	db.AutoMigrate(&AWSCodeCommit{})
	db.AutoMigrate(&CloudHSM{})
	db.AutoMigrate(&AmazonRekognition{})
	db.AutoMigrate(&AmazonCloudDirectory{})
	db.AutoMigrate(&AWSDirectConnect{})
	db.AutoMigrate(&AmazonWorkMail{})
	db.AutoMigrate(&AmazonRDS{})
	db.AutoMigrate(&OpsWorks{})
	db.AutoMigrate(&AmazonSES{})
	db.AutoMigrate(&AlexaWebInfoService{})
	db.AutoMigrate(&IngestionServiceSnowball{})
	db.AutoMigrate(&AmazonETS{})
	db.AutoMigrate(&AmazonCognito{})
	db.AutoMigrate(&SnowballExtraDays{})
	db.AutoMigrate(&CodeBuild{})
	db.AutoMigrate(&AmazonQuickSight{})

	return nil
}